require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FocusesController do

  # This should return the minimal set of attributes required to create a valid
  # Focus. As you add validations to Focus, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FocusesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all focuses as @focuses" do
      focus = Focus.create! valid_attributes
      get :index, {}, valid_session
      assigns(:focuses).should eq([focus])
    end
  end

  describe "GET show" do
    it "assigns the requested focus as @focus" do
      focus = Focus.create! valid_attributes
      get :show, {:id => focus.to_param}, valid_session
      assigns(:focus).should eq(focus)
    end
  end

  describe "GET new" do
    it "assigns a new focus as @focus" do
      get :new, {}, valid_session
      assigns(:focus).should be_a_new(Focus)
    end
  end

  describe "GET edit" do
    it "assigns the requested focus as @focus" do
      focus = Focus.create! valid_attributes
      get :edit, {:id => focus.to_param}, valid_session
      assigns(:focus).should eq(focus)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Focus" do
        expect {
          post :create, {:focus => valid_attributes}, valid_session
        }.to change(Focus, :count).by(1)
      end

      it "assigns a newly created focus as @focus" do
        post :create, {:focus => valid_attributes}, valid_session
        assigns(:focus).should be_a(Focus)
        assigns(:focus).should be_persisted
      end

      it "redirects to the created focus" do
        post :create, {:focus => valid_attributes}, valid_session
        response.should redirect_to(Focus.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved focus as @focus" do
        # Trigger the behavior that occurs when invalid params are submitted
        Focus.any_instance.stub(:save).and_return(false)
        post :create, {:focus => {}}, valid_session
        assigns(:focus).should be_a_new(Focus)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Focus.any_instance.stub(:save).and_return(false)
        post :create, {:focus => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested focus" do
        focus = Focus.create! valid_attributes
        # Assuming there are no other focuses in the database, this
        # specifies that the Focus created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Focus.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => focus.to_param, :focus => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested focus as @focus" do
        focus = Focus.create! valid_attributes
        put :update, {:id => focus.to_param, :focus => valid_attributes}, valid_session
        assigns(:focus).should eq(focus)
      end

      it "redirects to the focus" do
        focus = Focus.create! valid_attributes
        put :update, {:id => focus.to_param, :focus => valid_attributes}, valid_session
        response.should redirect_to(focus)
      end
    end

    describe "with invalid params" do
      it "assigns the focus as @focus" do
        focus = Focus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Focus.any_instance.stub(:save).and_return(false)
        put :update, {:id => focus.to_param, :focus => {}}, valid_session
        assigns(:focus).should eq(focus)
      end

      it "re-renders the 'edit' template" do
        focus = Focus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Focus.any_instance.stub(:save).and_return(false)
        put :update, {:id => focus.to_param, :focus => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested focus" do
      focus = Focus.create! valid_attributes
      expect {
        delete :destroy, {:id => focus.to_param}, valid_session
      }.to change(Focus, :count).by(-1)
    end

    it "redirects to the focuses list" do
      focus = Focus.create! valid_attributes
      delete :destroy, {:id => focus.to_param}, valid_session
      response.should redirect_to(focuses_url)
    end
  end

end
